# Generated by Django 5.2.3 on 2025-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCareApp', '0003_veterinarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('oprema', 'Oprema'), ('igracki', 'Igracki'), ('milenicinja', 'Milenicinja'), ('hrana', 'Hrana'), ('nega', 'Nega')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
